name: Deploy to Floci AKS

on:
  push:
    branches:
      - NP_Main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Cluster
        shell: powershell
        run: |
          kubectl get nodes

      - name: Apply Manifest
        shell: powershell
        run: |
          kubectl apply -f aks/app.yml

      - name: Restart Deployment
        shell: powershell
        run: |
          kubectl rollout restart deployment/userinfo-deployment

      - name: Wait for Rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/userinfo-deployment

      - name: Verify Service
        shell: powershell
        run: |
          kubectl get svc
