name: Deploy to Floci AKS

on:
  push:
    branches:
      - NP_Main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      KUBECONFIG: C:\Users\admin\.kube\config

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Runner
        shell: powershell
        run: |
          Write-Host "Runner: $env:COMPUTERNAME"
          Write-Host "User: $env:USERNAME"
          Write-Host "KUBECONFIG: $env:KUBECONFIG"

      - name: Verify kubectl
        shell: powershell
        run: |
          kubectl version --client
          kubectl config current-context
          kubectl get nodes

      - name: Apply Kubernetes Manifest
        shell: powershell
        run: |
          kubectl apply -f aks/app.yml

      - name: Restart Deployment
        shell: powershell
        run: |
          kubectl rollout restart deployment/userinfo-deployment

      - name: Wait for Rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/userinfo-deployment --timeout=180s

      - name: Verify Deployment
        shell: powershell
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get svc
